name: Using Cypress Github Action

on:
  push:
    branches:
      - main
      - develop
      - release/*

  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./test
        run : |
          npm install --force
          npm i fx -g
        
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./test
          command: npm run test |& tee cypress-logs.txt
          
      - run : ls && cd test && ls 
      - run : cat test/cypress-logs.txt
      - name: Generate list using Markdown
        run: cd ./test/reports && ls

