name: Using Cypress Github Action

on:
  push:
    branches:
      - main
      - develop
      - release/*

  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./test
        run : |
          npm install --force
          npm i fx -g
        
      - name: Cypress run
        uses: cypress-io/github-action@v4
        continue-on-error: true
        with:
          working-directory: ./test
          command: npm run cy:run -- --env TAGS='@smoke'


